sudo: required

services:
  - docker

before_install:
  - docker build -t sudheerasl/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run sudheerasl/react-test npm test -- --coverage

after_success:
  - docker build -t sudheerasl/multi-client ./client
  - docker build -t sudheerasl/multi-nginx ./nginx
  - docker build -t sudheerasl/multi-server ./server
  - docker build -t sudheerasl/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push sudheerasl/multi-client
  - docker push sudheerasl/multi-nginx
  - docker push sudheerasl/multi-server
  - docker push sudheerasl/multi-worker

